services:
  content-api:
    build:
      context: .
      args:
        - CACHE_BUST=20260501v6-fresh
    container_name: content-factory-v5
    ports:
      - "8085:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./firebase-admin.json:/app/firebase-admin.json:ro
      - ./content-factory-tts-494706-0880f6d00a88.json:/app/content-factory-tts-494706-0880f6d00a88.json:ro
      - ./output:/app/output
